# Generated by Django 5.2.5 on 2025-08-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='case_studies/')),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('results', models.TextField(help_text='List each result on a new line.')),
            ],
        ),
    ]
